
//login action types
export const LOGIN_USER_ID = "LOGIN_USER_ID";
export const LOGIN_USER_STATUS = "LOGIN_USER_STATUS";
export const SET_LOGIN_CREDENTIAL = "SET_LOGIN_CREDENTIAL";
export const CART_LIST_DATA = "CART_LIST_DATA";
export const CART_LIST_DATA1 = "CART_LIST_DATA1";
export const GET_ALL_SHOP = "GET_ALL_SHOP";
export const SET_BRAND_LOADER = "SET_BRAND_LOADER";
export const SET_PRODUCT_LOADER = "SET_PRODUCT_LOADER";
export const SET_PRODUCT3_LOADER = "SET_PRODUCT3_LOADER";
export const SET_PRODUCT2_LOADER = "SET_PRODUCT2_LOADER";
export const SET_CHECKOUT_LOADER = "SET_CHECKOUT_LOADER";
export const SET_CATEGORY_LOADER = "SET_CATEGORY_LOADER";
export const SET_SUPPORT_LOADER = "SET_SUPPORT_LOADER";
export const SET_COMMENT_LOADER = "SET_COMMENT_LOADER";
export const LIVE_LIST_DATA = "LIVE_LIST_DATA";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_WatchPRODUCT = "GET_ALL_WatchPRODUCT";
export const GET_ALL_PRODUCTDETAILS = "GET_ALL_PRODUCTDETAILS";
export const SET_ADDCART_LOADER = "SET_ADDCART_LOADER";
export const SET_SCHEDULE_LOADER = "SET_SCHEDULE_LOADER";
export const INCREMENT_CART_LIST = "INCREMENT_CART_LIST";
export const DELETE_CART_LIST = "DELETE_CART_LIST";
export const REMOVE_CATEGORY_LIST = "REMOVE_CATEGORY_LIST";
export const REMOVE_ITEM_LIST = "REMOVE_ITEM_LIST";
export const GET_SUPPORT_LIST1 = "GET_SUPPORT_LIST1";
export const GET_PROFILEUSER_LIST = "GET_PROFILEUSER_LIST";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GETCALLTOKEN = "GETCALLTOKEN";
export const DELETE_USER = "DELETE_USER";
export const SEARCH_LIST_ITMES = "SEARCH_LIST_ITMES";
export const ALLSEARCH_LIST_DATA = "ALLSEARCH_LIST_DATA";

export const GET_INCOMINGORDER_LIST = "GET_INCOMINGORDER_LIST";
export const GET_PROCESSORDER_LIST = "GET_PROCESSORDER_LIST";
export const GET_LIVEEVENT_LIST = "GET_LIVEEVENT_LIST";
export const GET_LIVECOMMENT_LIST ="GET_LIVECOMMENT_LIST";
export const SET_CATEGORYPRODUCT_LOADER ="SET_CATEGORYPRODUCT_LOADER";
export const SET_UPDATEPROFILE_LOADER = "SET_UPDATEPROFILE_LOADER";
export const SET_UPDATEPASSWORD_LOADER = "SET_UPDATEPASSWORD_LOADER";
export const COUNTRY_LIST_DATA = "COUNTRY_LIST_DATA";
export const BRANDS_LIST_DATA = "BRANDS_LIST_DATA";
export const ALLEVENT_LIST_DATA = "ALLEVENT_LIST_DATA";
export const GET_BRAND_DETAILS ="GET_BRAND_DETAILS";
export const GET_BRAND_PRODUCT ="GET_BRAND_PRODUCT";
export const GET_SELL_DESHBOARD = "GET_SELL_DESHBOARD";
export const GET_TOP_SELL = "GET_TOP_SELL";
export const GET_TOP_COUNTRY = "GET_TOP_COUNTRY";
export const GET_SHOP_PRODUCT = "GET_SHOP_PRODUCT";
export const GET_SHOPSELL_COUNT = "GET_SHOPSELL_COUNT";
export const NEW_PROFILE = "NEW_PROFILE";
export const SET_SAVEADDRESS_LOADER = "SET_SAVEADDRESS_LOADER";
export const GET_USERADDRESS_LIST = "GET_USERADDRESS_LIST";
export const DELETE_ADDRESS_LIST = "DELETE_ADDRESS_LIST";
export const DELETE_CARD_LIST = "DELETE_CARD_LIST";
export const GET_USERCARD_LIST = "GET_USERCARD_LIST";

export const SET_USER_INFO = "SET_USER_INFO";
export const SET_LOGIN_LOADER = "SHOW_LOGIN_LOADER";
export const SET_PHONESIGNUP_LOADER = "SET_PHONESIGNUP_LOADER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const CHANGE_REMBER_ME_LOGIN_CREDENTIALS = "CHANGE_REMBER_ME_LOGIN_CREDENTIALS";
export const SET_DEFAULT_AUTH_SCREEN = "SET_DEFAULT_AUTH_SCREEN";
export const SET_NETWORK_STATE = "SET_NETWORK_STATE";

//forget password/reset password
export const SET_FORGET_PASSWORD_LOADER = "SET_FORGET_PASSWORD_LOADER";
export const SET_RESET_PASSWORD_LOADER = "SET_RESET_PASSWORD_LOADER";
export const SET_FORGET_PASSWORD_SUCCESS = "SET_FORGET_PASSWORD_SUCCESS";
export const SET_RESET_PASSWORD_SUCCESS = "SET_RESET_PASSWORD_SUCCESS";

//registration action types
export const SET_REGISTRATION_LOADER = "SHOW_REGISTRATION_LOADER";
export const SET_REGISTRATION_ERROR = "SET_REGISTRATION_ERROR";
export const SIGNUP_CREDENTIALS = "SIGNUP_CREDENTIALS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const VENDOR_REQUEST_LOADER = "VENDOR_REQUEST_LOADER";
export const VENDOR_REQUESTED_INFO = "VENDOR_REQUESTED_INFO";

//OTP Verification 
export const SET_OTP_LOADER = "SET_OTP_LOADER";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS";

//Vendor
export const SET_VENDOR_LOADER = "SET_VENDOR_LOADER";
export const VENDOR_ADDED_SUCCESS = "OTP_RESEND_SUCCESS";
export const VENDOR_ADDED_INFO = "VENDOR_ADDED_INFO";
export const SET_VENDOR_LIST = "SET_VENDOR_LIST";
export const SET_VENDOR_LIST_LOADER = "SET_VENDOR_LIST_LOADER";

export const VENDOR_UPDATE_LOADER = "VENDOR_UPDATE_LOADER";
export const VENDOR_UPDATED_INFO = "VENDOR_UPDATED_INFO";

export const SET_SINGLE_VENDOR_LOADER = "SET_SINGLE_VENDOR_LOADER";
export const SET_SINGLE_VENDOR_INFO = "SET_SINGLE_VENDOR_INFO";

export const ACCEPT_VENDOR_LOADER = "SET_SINGLE_VENDOR_LOADER";
export const ACCEPT_VENDOR_INFO = "ACCEPT_VENDOR_INFO";

export const SET_CREATE_STORE_LOADER = "SET_CREATE_STORE_LOADER";
export const SET_CREATE_STORE_INFO = "SET_CREATE_STORE_INFO";
export const SET_UTILITYBILL_LOADER = "SET_UTILITYBILL_LOADER";
export const SET_UTILITYBILL_INFO = "SET_UTILITYBILL_INFO";
export const SET_STOREIMAGE_LOADER = "SET_STOREIMAGE_LOADER";
export const SET_STOREIMAGE_INFO = "SET_STOREIMAGE_INFO";
export const SET_STORE_AUTOFILL_INFO = "SET_STORE_AUTOFILL_INFO";
export const SET_VENDOR_NOTIFICATION_INFO = "SET_VENDOR_NOTIFICATION_INFO";

export const SET_USER_ID_RESET_PASSWORD = "SET_USER_ID_RESET_PASSWORD";

export const SET_TRACK_EARNING_LOADER = "SET_TRACK_EARNING_LOADER";
export const SET_TRACK_EARNING_DATA = "SET_TRACK_EARNING_DATA";
export const SET_VERIFICAITON_STATUS = "SET_VERIFICAITON_STATUS";
export const SET_VERIFICAITON_STEPS = "SET_VERIFICAITON_STEPS";


// Search Category (Business Type)
export const SET_SEARCH_CATEGORY_LOADER = "SET_SEARCH_CATEGORY_LOADER";
export const SET_SEARCH_CATEGORY_RESULT = "SET_SEARCH_CATEGORY_RESULT";

//Coupons
export const CREATE_COUPONS_SUCCESS = "CREATE_COUPONS_SUCCESS";
export const CREATE_COUPONS_LOADER = "CREATE_COUPONS_LOADER";

export const COUPONS_LIST_LOADER = "COUPONS_LIST_LOADER";
export const SET_COUPONS_LIST = "SET_COUPONS_LIST";

export const REDEEMED_COUPONS_LOADER = "REDEEMED_COUPONS_LOADER";
export const SET_REDEEMED_COUPONS = "SET_REDEEMED_COUPONS";

export const REDEEMED_COUPONS_TRACKING_LOADER = "REDEEMED_COUPONS_TRACKING_LOADER";
export const SET_REDEEMED_TRACKING_COUPONS = "SET_REDEEMED_TRACKING_COUPONS";
export const SET_IS_STORE = "SET_IS_STORE";

export const SUBSCRIPTION_PLAN_DATA= "SUBSCRIPTION_PLAN_DATA";
export const SUBSCRIPTION_PLAN_DATA_LOADER= "SUBSCRIPTION_PLAN_DATA_LOADER";
export const SUBSCRIPTION_STATUS= "SUBSCRIPTION_STATUS";
export const SUBSCRIPTION_PURCHASED_DATA= "SUBSCRIPTION_PURCHASED_DATA";
export const SUBSCRIPTION_PURCHASED_LOADER= "SUBSCRIPTION_PURCHASED_LOADER";
export const SET_PLAN_SELECTED_FLAG= "SET_PLAN_SELECTED_FLAG";
export const SET_REMAING_COUPON_CREDIT= "SET_REMAING_COUPON_CREDIT";

export const SET_PAYMENT_PROCESS= "SET_REMAING_COUPON_CREDIT";
export const PAYMENT_PROCESS_LOADER= "PAYMENT_PROCESS_LOADER";

//Banks
export const GET_BANKS_LOADER = "GET_BANKS_LOADER";
export const GET_BANKS = "GET_BANKS";

export const ADD_NEW_BANK_ACCOUNT_LOADER = "ADD_NEW_BANK_ACCOUNT_LOADER";
export const ADDED_BANK_INFO = "ADDED_BANK_INFO";

export const BANK_ACCOUNT_LIST_LOADER = "BANK_ACCOUNT_LIST_LOADER";
export const BANK_ACCOUNT_LIST = "BANK_ACCOUNT_LIST";

export const UPDATED_BANK_ACCOUNT_INFO = "UPDATED_BANK_ACCOUNT_INFO";
export const UPDATE_BANK_ACCOUNT_LOADER = "UPDATE_BANK_ACCOUNT_LOADER";
export const SET_BRAND_NAME = "SET_BRAND_NAME"; 
export const GET_CHANNEL_COUNT = "GET_CHANNEL_COUNT";
export const TOTAL_CART_PRICE = "TOTAL_CART_PRICE";
export const LIVESTREAM_RECAP = "LIVESTREAM_RECAP";
export const SET_RATING_REVIEW = "SET_RATING_REVIEW";
export const GET_ALL_RATING = "GET_ALL_RATING";


