require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'WallPon' do
  # pod 'react-native-ffmpeg/video', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
  
  config = use_native_modules!
  #rn_maps_path = '../node_modules/react-native-maps'
  #pod 'react-native-google-maps', :path => rn_maps_path
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'rn-fetch-blob',
      :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'react-native-agora', :path => '../node_modules/react-native-agora'


  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'RNCClipboard', :path => '../node_modules/@react-native-community/clipboard'

  # pod 'RNBraintreeDropIn', :path => '../node_modules/react-native-braintree-dropin-ui'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'WallPonTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end
